// SVG Illustrations for Pricing Packages

export const OnePageIllustration = () => (
  <svg
    width="88"
    height="88"
    viewBox="0 0 88 88"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className="drop-shadow-md"
  >
    <defs>
      <linearGradient
        id="onePageGrad"
        x1="0"
        y1="0"
        x2="88"
        y2="88"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#3B82F6" />
        <stop offset="1" stopColor="#06B6D4" />
      </linearGradient>
    </defs>
    <rect
      x="6"
      y="6"
      width="76"
      height="76"
      rx="16"
      fill="url(#onePageGrad)"
      opacity="0.15"
    />
    <rect
      x="18"
      y="18"
      width="52"
      height="52"
      rx="10"
      fill="white"
      className="dark:fill-gray-900"
    />
    <rect
      x="24"
      y="24"
      width="40"
      height="6"
      rx="3"
      fill="#60A5FA"
      className="dark:fill-blue-500"
    />
    <rect
      x="24"
      y="36"
      width="32"
      height="4"
      rx="2"
      fill="#93C5FD"
      className="dark:fill-blue-400"
    />
    <rect
      x="24"
      y="44"
      width="28"
      height="4"
      rx="2"
      fill="#BAE6FD"
      className="dark:fill-cyan-400/70"
    />
    <rect
      x="24"
      y="52"
      width="20"
      height="4"
      rx="2"
      fill="#E0F2FE"
      className="dark:fill-cyan-300/70"
    />
  </svg>
);

export const MultiPageIllustration = () => (
  <svg
    width="88"
    height="88"
    viewBox="0 0 88 88"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className="drop-shadow-md"
  >
    <defs>
      <linearGradient
        id="multiPageGrad"
        x1="0"
        y1="0"
        x2="88"
        y2="88"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8B5CF6" />
        <stop offset="1" stopColor="#6366F1" />
      </linearGradient>
    </defs>
    <rect
      x="6"
      y="6"
      width="76"
      height="76"
      rx="16"
      fill="url(#multiPageGrad)"
      opacity="0.15"
    />
    <g>
      <rect
        x="18"
        y="18"
        width="24"
        height="24"
        rx="6"
        fill="white"
        className="dark:fill-gray-900"
      />
      <rect
        x="46"
        y="18"
        width="24"
        height="24"
        rx="6"
        fill="white"
        className="dark:fill-gray-900"
      />
      <rect
        x="18"
        y="46"
        width="24"
        height="24"
        rx="6"
        fill="white"
        className="dark:fill-gray-900"
      />
      <rect
        x="46"
        y="46"
        width="24"
        height="24"
        rx="6"
        fill="white"
        className="dark:fill-gray-900"
      />
      <rect
        x="24"
        y="24"
        width="12"
        height="4"
        rx="2"
        fill="#C4B5FD"
        className="dark:fill-violet-400"
      />
      <rect
        x="52"
        y="24"
        width="12"
        height="4"
        rx="2"
        fill="#C4B5FD"
        className="dark:fill-violet-400"
      />
      <rect
        x="24"
        y="52"
        width="12"
        height="4"
        rx="2"
        fill="#C4B5FD"
        className="dark:fill-violet-400"
      />
      <rect
        x="52"
        y="52"
        width="12"
        height="4"
        rx="2"
        fill="#C4B5FD"
        className="dark:fill-violet-400"
      />
    </g>
  </svg>
);

export const EnterpriseIllustration = () => (
  <svg
    width="88"
    height="88"
    viewBox="0 0 88 88"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className="drop-shadow-md"
  >
    <defs>
      <linearGradient
        id="enterpriseGrad"
        x1="0"
        y1="0"
        x2="88"
        y2="88"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#10B981" />
        <stop offset="1" stopColor="#14B8A6" />
      </linearGradient>
    </defs>
    <rect
      x="6"
      y="6"
      width="76"
      height="76"
      rx="16"
      fill="url(#enterpriseGrad)"
      opacity="0.15"
    />
    {/* Main building structure */}
    <rect
      x="16"
      y="24"
      width="56"
      height="48"
      rx="6"
      fill="white"
      className="dark:fill-gray-900"
    />
    {/* Building top */}
    <rect
      x="16"
      y="16"
      width="56"
      height="10"
      rx="5"
      fill="#10B981"
      className="dark:fill-emerald-500"
    />
    {/* Windows grid - 3 rows x 4 columns */}
    <g>
      <rect
        x="22"
        y="32"
        width="8"
        height="8"
        rx="2"
        fill="#D1FAE5"
        className="dark:fill-emerald-200/30"
      />
      <rect
        x="34"
        y="32"
        width="8"
        height="8"
        rx="2"
        fill="#D1FAE5"
        className="dark:fill-emerald-200/30"
      />
      <rect
        x="46"
        y="32"
        width="8"
        height="8"
        rx="2"
        fill="#D1FAE5"
        className="dark:fill-emerald-200/30"
      />
      <rect
        x="58"
        y="32"
        width="8"
        height="8"
        rx="2"
        fill="#D1FAE5"
        className="dark:fill-emerald-200/30"
      />

      <rect
        x="22"
        y="44"
        width="8"
        height="8"
        rx="2"
        fill="#A7F3D0"
        className="dark:fill-emerald-300/40"
      />
      <rect
        x="34"
        y="44"
        width="8"
        height="8"
        rx="2"
        fill="#A7F3D0"
        className="dark:fill-emerald-300/40"
      />
      <rect
        x="46"
        y="44"
        width="8"
        height="8"
        rx="2"
        fill="#A7F3D0"
        className="dark:fill-emerald-300/40"
      />
      <rect
        x="58"
        y="44"
        width="8"
        height="8"
        rx="2"
        fill="#A7F3D0"
        className="dark:fill-emerald-300/40"
      />

      <rect
        x="22"
        y="56"
        width="8"
        height="8"
        rx="2"
        fill="#6EE7B7"
        className="dark:fill-emerald-400/50"
      />
      <rect
        x="34"
        y="56"
        width="8"
        height="8"
        rx="2"
        fill="#6EE7B7"
        className="dark:fill-emerald-400/50"
      />
      <rect
        x="46"
        y="56"
        width="8"
        height="8"
        rx="2"
        fill="#6EE7B7"
        className="dark:fill-emerald-400/50"
      />
      <rect
        x="58"
        y="56"
        width="8"
        height="8"
        rx="2"
        fill="#6EE7B7"
        className="dark:fill-emerald-400/50"
      />
    </g>
    {/* Door */}
    <rect
      x="38"
      y="64"
      width="12"
      height="8"
      rx="2"
      fill="#10B981"
      className="dark:fill-emerald-600"
    />
  </svg>
);
